name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

        language: node_js
        node_js: - "12"

        addons:
            apt:
              sources:
                - google-chrome
              packages:
                - google-chrome-stable

            cache:
                  directories:
                      - ./node_modules

                  install:
                          - npm install

                  script:
                        - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
